version: "3.8"

services:
  mysql_project:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_project:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  mysql_project:
